Propertymanagerment/Propertymanagerment/Areas/Admin/Controllers/Full_ContractAdminController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Transactions;
using System.Web;
using System.Web.Mvc;
using PropertyManagerment.Models;

namespace PropertyManagerment.Areas.Admin.Controllers
{
    public class Full_ContractAdminController : Controller
    {
        private PPCDBEntities db = new PPCDBEntities();

        // GET: Admin/Full_Contract
        public ActionResult Index()
        {
            var full_Contract = db.Full_Contract.Include(f => f.Property);
            return View(full_Contract.ToList());
        }


        // GET: Admin/Full_Contract/Create
        public ActionResult Create(int id)
        {
            //Property property = model.Properties.FirstOrDefault(x => x.ID == id);
            //var inOrder_Installment = model.Installment_Contract.Where(x => x.Property_ID == id);
            //var inOrder_FullContact = model.Full_Contract.Where(x => x.Property_ID == id);
            //var orn = model.Property_Service.Where(x => x.Property_ID == property.ID).ToArray();
            //if (inOrder_FullContact.Count() != 0 || inOrder_Installment.Count() != 0)
            //{
            //    TempData["msg"] = "<script>alert('BẤT ĐỘNG SẢN HIỆN ĐANG TRONG QUÁ TRÌNH CÓ HỢP ĐỒNG!!! VUI LÒNG QUAY LẠI.');</script>";
            //}
            //else
            //{
            //    for (int i = 0; i < orn.Length; i++)
            //    {
            //        var tmp = orn[i];
            //        Property_Service psDell = model.Property_Service.FirstOrDefault(x => x.Property_ID == tmp.Property_ID);
            //        model.Property_Service.Remove(psDell);
            //        model.SaveChanges();

            //    }
            //    model.Properties.Remove(property);
            //    model.SaveChanges();
            //    PopularMessage(true);
            //    return RedirectToAction("Index");
            //}
            //PopularMessage(false);
            //return View(property);

            var property = db.Properties.FirstOrDefault(x => x.ID == id);
            dateYearOfBirth();

            if (property != null)
            {
                var fc = new Full_Contract();
                fc.Price = property.Price;
                ViewData["PP_Code"] = property.Property_Code;
                return View(fc);
            }
            else
            {
                return View();
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Customer_Name,Year_Of_Birth,SSN,Customer_Address," +
            "Mobile,Price,Deposit,Remain")] Full_Contract contract, string Property_Code)
        {
            var property = db.Properties.FirstOrDefault(m => m.Property_Code.Equals(Property_Code.ToString()));
            int Property_ID = property.ID;
            if (ModelState.IsValid)
            {
                using (var scope = new TransactionScope())
                {
                    contract.Property_ID = Property_ID;
                    contract.Remain = contract.Price - contract.Deposit;
                    contract.Status = false;
                    contract.Date_Of_Contract = DateTime.Now;
                    db.Full_Contract.Add(contract);
                    db.SaveChanges();
                    scope.Complete();
                }

                return RedirectToAction("Index");
            }
            dateYearOfBirth();

            return View("NewContract", contract);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Full_Contract contract, string Mobile, string Customer_Name, decimal Deposit, decimal Remain, string Address, string ssn )
        {
            if (ModelState.IsValid)
            {
                contract = db.Full_Contract.FirstOrDefault(x => x.ID == contract.ID);
                contract.Customer_Name = Customer_Name;
                contract.Mobile = Mobile;
                contract.Deposit = Deposit;
                contract.Customer_Address = Address;
                contract.Remain = contract.Price - contract.Deposit;
                contract.SSN = ssn;
                contract.Date_Of_Contract = DateTime.Now;
                db.Entry(contract).State = EntityState.Modified;         
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View("Edit", contract);
        }

        // GET: Admin/Full_Contract/Delete/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("index", "notfound");
            }
            Full_Contract contract = db.Full_Contract.FirstOrDefault(x => x.ID == id);

            if (contract == null)
            {
                return RedirectToAction("index", "notfound");
            }
            return View(contract);
        }

        // POST: Admin/Full_Contract/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("index", "notfound");
            }
            Full_Contract fc = db.Full_Contract.FirstOrDefault(x => x.ID == id);

            if (fc == null)
            {
                return RedirectToAction("index", "notfound");
            }
            return View(fc);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Full_Contract contract = db.Full_Contract.FirstOrDefault(x => x.ID == id);
            db.Full_Contract.Remove(contract);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult Print(int id)
        {
            var contract = db.Full_Contract.FirstOrDefault(n => n.ID == id);
            if (contract != null)
            {
                FullContractPrintModel fc = new FullContractPrintModel();
                fc.Customer_Name = contract.Customer_Name;
                fc.Customer_Address = contract.Customer_Address;
                fc.Date_of_Contract = contract.Date_Of_Contract;
                fc.Deposit = contract.Deposit;
                fc.Mobile = contract.Mobile;
                fc.Price = contract.Price;
                fc.Property_Code = contract.Property.Property_Code;
                fc.SSN = contract.SSN;
                fc.Address = contract.Property.Address; ;
                fc.Full_Contract_Code = contract.Full_Contract_Code;
                return View(fc);
            }
            else
            {
                return View();                                                                                           
            }
        }
        public void dateYearOfBirth()
        {
            ViewBag.Year_Of_Birth = new SelectList(Enumerable.Range(1900, (DateTime.Now.Year - 1900) + 1));
        }
    }
}

Propertymanagerment/Propertymanagerment/Areas/Admin/Views/Full_ContractAdmin/Create.cshtml
@model PropertyManagerment.Models.Full_Contract

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>THÊM HỢP ĐỒNG THANH TOÁN ĐẦY ĐỦ</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="@Url.Action("Index", "PropertyAdmin")">DANH SÁCH BẤT ĐỘNG SẢN</a></li>
                    <li class="breadcrumb-item active">Thêm hợp đồng đầy đủ</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.Full_Contract_Code, new { htmlAttributes = new { @class = "form-control" } })





    @*<div class="form-group">
        @Html.LabelFor(model => model.Customer_Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Customer_Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Customer_Name, "", new { @class = "text-danger" })
        </div>
    </div>*@

    @*<div class="form-group">
        @Html.LabelFor(model => model.Year_Of_Birth, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Year_Of_Birth, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Year_Of_Birth, "", new { @class = "text-danger" })
        </div>
    </div>*@

    @*<div class="form-group">
        @Html.LabelFor(model => model.SSN, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SSN, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SSN, "", new { @class = "text-danger" })
        </div>
    </div>*@

    @*<div class="form-group">
        @Html.LabelFor(model => model.Customer_Address, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Customer_Address, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Customer_Address, "", new { @class = "text-danger" })
        </div>
    </div>*@

    @*<div class="form-group">
        @Html.LabelFor(model => model.Mobile, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Mobile, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Mobile, "", new { @class = "text-danger" })
        </div>
    </div>*@

    @*<div class="form-group">
        @Html.LabelFor(model => model.Property_ID, "Property_ID", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("Property_ID", null, htmlAttributes: new { @class = "form-control", @disabled = "disabled" })
            @Html.ValidationMessageFor(model => model.Property_ID, "", new { @class = "text-danger" })
        </div>
    </div>*@

    @*<div class="form-group">
        @Html.LabelFor(model => model.Date_Of_Contract, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Date_Of_Contract, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Date_Of_Contract, "", new { @class = "text-danger" })
        </div>
    </div>*@

    @*<div class="form-group">
        @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
        </div>
    </div>*@

    @*<div class="form-group">
        @Html.LabelFor(model => model.Deposit, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Deposit, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Deposit, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Remain, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Remain, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Remain, "", new { @class = "text-danger" })
        </div>
    </div>*@

    @*<div class="form-group">
        @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Status)
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>*@

    <div class="col-12">
        <div class="card card-danger">
            <div class="card-header">
                <div class="card-title">
                    <h3 class="card-title">THÔNG TIN KHÁCH HÀNG</h3>
                </div>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label> TÊN KHÁCH HÀNG</label>
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Customer_Name, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Customer_Name, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label> NĂM SINH KHÁCH HÀNG </label>
                            <div class="col-md-10">
                                @Html.DropDownList("Year_Of_Birth", null, htmlAttributes: new { @class = "form-control" })

                            </div>
                        </div>
                        <div class="form-group">
                            <label> SỐ ĐIỆN THOẠI KHÁCH HÀNG </label>
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Mobile, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Mobile, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="form-group">
                            <label> CHỨNG MINH NHÂN DÂN  </label>
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.SSN, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.SSN, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <!-- /.form-group -->
                        <div class="form-group">
                            <label> ĐỊA CHỈ CƯ TRÚ  </label>
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Customer_Address, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Customer_Address, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-12">
        <div class="card card-primary">
            <div class="card-header">
                <div class="card-title">
                    <h3 class="card-title">
                  
                      
                            THÔNG TIN HỢP ĐỒNG BẤT ĐỘNG SẢN
                      
                    
                     
                    </h3>
                </div>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label> MÃ SỐ BẤT ĐỘNG SẢN</label>
                            <div class="col-md-10">
                                @Html.TextBox("Property_Code", ViewData["PP_Code"], new { @class = "form-control", @readonly = "@readonly" })

                            </div>
                        </div>
                     
                        <div class="form-group">
                            <label>GIÁ BÁN CỦA BẤT ĐỘNG SẢN</label>
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })

                            </div>
                        </div>
                        <div class="form-group">
                            <label>SỐ TIỀN ĐÃ CỌC</label>
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Deposit, new { htmlAttributes = new { @class = "form-control" } })

                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label> SỐ TIỀN CÒN LẠI </label>
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Remain, new { htmlAttributes = new { @class = "form-control" } })

                            </div>
                        </div>
                    
                   
                        <div class="form-group">
                            <label>TRẠNG THÁI HỢP ĐỒNG</label>
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Status)


                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    
    
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Tạo hợp đồng" class="btn btn-primary" style="margin-left:5%" />
            <div class="btn btn-warning" style="margin-left:50%">@Html.ActionLink("Quay lại", "Index")</div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Propertymanagerment/Propertymanagerment/Areas/Admin/Views/Full_ContractAdmin/Delete.cshtml
@model PropertyManagerment.Models.Full_Contract

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Full_Contract</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Full_Contract_Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Full_Contract_Code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Customer_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customer_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Year_Of_Birth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Year_Of_Birth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SSN)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SSN)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Customer_Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customer_Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Mobile)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mobile)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date_Of_Contract)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date_Of_Contract)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Deposit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Deposit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Remain)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Remain)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Property.Property_Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Property.Property_Code)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Propertymanagerment/Propertymanagerment/Areas/Admin/Views/Full_ContractAdmin/Index.cshtml
@model IEnumerable<PropertyManagerment.Models.Full_Contract>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

@*<h2>Index</h2>

    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Full_Contract_Code)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Customer_Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Year_Of_Birth)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SSN)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Customer_Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Mobile)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date_Of_Contract)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Deposit)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Remain)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Property.Property_Code)
            </th>
            <th></th>
        </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Full_Contract_Code)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Customer_Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Year_Of_Birth)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SSN)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Customer_Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Mobile)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date_Of_Contract)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Deposit)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Remain)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Property.Property_Code)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
                @Html.ActionLink("Details", "Details", new { id=item.ID }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.ID })
            </td>
        </tr>
    }

    </table>*@

<h2 style="text-align:center">DANH SÁCH HỢP ĐỒNG ĐẦY ĐỦ</h2>
@if (Session["success"] != null)
{
    <div class="alert alert-success alert-dismissible" role="alert">

        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <strong>Well done!</strong> @Session["success"]
    </div>
}

<p>
  
</p>
<table class="table table-bordered table-striped" id="example1">
    <thead>
        <tr>
            <th>
                Mã hợp đồng
            </th>
            <th>
                Mã Bất động sản
            </th>
            <th>
                Tên Khách Hàng
            </th>
            <th>
                Số điện thoại
            </th>
            <th>
                Ngày lập hợp đồng
            </th>
            <th>
                Giá trị hợp đồng
            </th>
            <th>
                Trạng thái hợp đồng
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Full_Contract_Code)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Property.Property_Code)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Customer_Name)
            </td>


            <td>
                @Html.DisplayFor(modelItem => item.Mobile)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date_Of_Contract)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                <a href="@Url.Action("Print", "Full_ContractAdmin", new { id = item.ID })" target="_blank">
                    <button class="print-button">
                        <span class="print-icon"></span>
                    </button>|
                </a>
            </td>

            <td>
                <button type="button" class="btn btn-primary"> @Html.ActionLink("Cập nhật", "Edit", new { id = item.ID }) </button>
            </td>
            <td>
                @Html.ActionLink(" ", "Delete", new { id = item.ID }, new { @class = "fa fa-trash" })
            </td>
        </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <th>
                Mã hợp đồng
            </th>
            <th>
                Mã Bất động sản
            </th>
            <th>
                Tên Khách Hàng
            </th>
            <th>
                Số điện thoại
            </th>
            <th>
                Ngày lập hợp đồng
            </th>
            <th>
                Giá trị hợp đồng
            </th>
            <th>
                Trạng thái hợp đồng
            </th>
            <th></th>
        </tr>
    </tfoot>
</table>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $(function () {
            $(document).on('click', '[data-toggle="lightbox"]', function (event) {
                event.preventDefault();
                $(this).ekkoLightbox({
                    alwaysShowClose: true
                });
            });

            $('.filter-container').filterizr({ gutterPixels: 3 });
            $('.btn[data-filter]').on('click', function () {
                $('.btn[data-filter]').removeClass('active');
                $(this).addClass('active');
            });
        })
    </script>
}