Propertymanagerment/Propertymanagerment/Models/Installment_Contract.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Propertymanagerment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Installment_Contract
    {
        public int ID { get; set; }
        public string Installment_Contract_Code { get; set; }
        public string Customer_Name { get; set; }
        public Nullable<int> Year_Of_Birth { get; set; }
        public string SSN { get; set; }
        public string Customer_Address { get; set; }
        public string Mobile { get; set; }
        public int Property_ID { get; set; }
        public Nullable<System.DateTime> Date_Of_Contract { get; set; }
        public string Installment_Payment_Method { get; set; }
        public Nullable<int> Payment_Period { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Deposit { get; set; }
        public Nullable<decimal> Loan_Amount { get; set; }
        public Nullable<decimal> Taken { get; set; }
        public Nullable<decimal> Remain { get; set; }
        public bool Status { get; set; }
    
        public virtual Property Property { get; set; }
    }
}

Propertymanagerment/Propertymanagerment/Areas/Admin/Controllers/InstallmentContractController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Propertymanagerment.Models;

namespace PropertyManagerment.Areas.Admin.Controllers
{
    public class InstallmentContractController : Controller
    {
        private PPCDBEntities db = new PPCDBEntities();

        // GET: Admin/Installment_ContractAdmin
        public ActionResult Index()
        {
            var installment_Contract = db.Installment_Contract.Include(i => i.Property);
            return View(installment_Contract.ToList());
        }

        // GET: Admin/Installment_ContractAdmin/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Installment_Contract installment_Contract = db.Installment_Contract.Find(id);
            if (installment_Contract == null)
            {
                return HttpNotFound();
            }
            return View(installment_Contract);
        }

        // GET: Admin/Installment_ContractAdmin/Create
        public ActionResult Create()
        {
            ViewBag.Property_ID = new SelectList(db.Properties, "ID", "Property_Code");
            return View();
        }

        // POST: Admin/Installment_ContractAdmin/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Installment_Contract_Code,Customer_Name,Year_Of_Birth,SSN,Customer_Address,Mobile,Property_ID,Date_Of_Contract,Installment_Payment_Method,Payment_Period,Price,Deposit,Loan_Amount,Taken,Remain,Status")] Installment_Contract installment_Contract)
        {
            if (ModelState.IsValid)
            {
                db.Installment_Contract.Add(installment_Contract);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Property_ID = new SelectList(db.Properties, "ID", "Property_Code", installment_Contract.Property_ID);
            return View(installment_Contract);
        }

        // GET: Admin/Installment_ContractAdmin/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Installment_Contract installment_Contract = db.Installment_Contract.Find(id);
            if (installment_Contract == null)
            {
                return HttpNotFound();
            }
            ViewBag.Property_ID = new SelectList(db.Properties, "ID", "Property_Code", installment_Contract.Property_ID);
            return View(installment_Contract);
        }

        // POST: Admin/Installment_ContractAdmin/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Installment_Contract_Code,Customer_Name,Year_Of_Birth,SSN,Customer_Address,Mobile,Property_ID,Date_Of_Contract,Installment_Payment_Method,Payment_Period,Price,Deposit,Loan_Amount,Taken,Remain,Status")] Installment_Contract installment_Contract)
        {
            if (ModelState.IsValid)
            {
                db.Entry(installment_Contract).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Property_ID = new SelectList(db.Properties, "ID", "Property_Code", installment_Contract.Property_ID);
            return View(installment_Contract);
        }

        // GET: Admin/Installment_ContractAdmin/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Installment_Contract installment_Contract = db.Installment_Contract.Find(id);
            if (installment_Contract == null)
            {
                return HttpNotFound();
            }
            return View(installment_Contract);
        }

        // POST: Admin/Installment_ContractAdmin/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Installment_Contract installment_Contract = db.Installment_Contract.Find(id);
            db.Installment_Contract.Remove(installment_Contract);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult Print(int id)
        {
            var contract = db.Installment_Contract.FirstOrDefault(n => n.ID == id);
            if (contract != null)
            {
                InstallmentContractPrintModel fc = new InstallmentContractPrintModel();
                fc.Customer_Name = contract.Customer_Name;
                fc.Customer_Address = contract.Customer_Address;
                fc.Date_Of_Contract = contract.Date_Of_Contract;
                fc.Deposit = contract.Deposit;
                fc.Mobile = contract.Mobile;
                fc.Price = contract.Price;
                fc.Property_Code = contract.Property.Property_Code;
                fc.SSN = contract.SSN;
                fc.Address = contract.Property.Address; ;
                fc.Installment_Contract_Code = contract.Installment_Contract_Code;
                return View(fc);
            }
            else
            {
                return View();
            }
        }
    }
}

Propertymanagerment/Propertymanagerment/Areas/Admin/Views/InstallmentContract/Create.cshtml
@model Propertymanagerment.Models.Installment_Contract

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Installment_Contract</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Installment_Contract_Code, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Installment_Contract_Code, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Installment_Contract_Code, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Customer_Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Customer_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Customer_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Year_Of_Birth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Year_Of_Birth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Year_Of_Birth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SSN, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SSN, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SSN, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Customer_Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Customer_Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Customer_Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mobile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mobile, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mobile, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Property_ID, "Property_ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Property_ID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Property_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date_Of_Contract, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date_Of_Contract, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date_Of_Contract, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Installment_Payment_Method, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Installment_Payment_Method, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Installment_Payment_Method, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Payment_Period, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Payment_Period, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Payment_Period, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Deposit, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Deposit, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Deposit, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Loan_Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Loan_Amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Loan_Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Taken, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Taken, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Taken, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Remain, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Remain, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Remain, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Status)
                    @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Propertymanagerment/Propertymanagerment/Areas/Admin/Views/InstallmentContract/Delete.cshtml
@model Propertymanagerment.Models.Installment_Contract

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Installment_Contract</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Installment_Contract_Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Installment_Contract_Code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Customer_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customer_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Year_Of_Birth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Year_Of_Birth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SSN)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SSN)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Customer_Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customer_Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Mobile)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mobile)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date_Of_Contract)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date_Of_Contract)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Installment_Payment_Method)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Installment_Payment_Method)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Payment_Period)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Payment_Period)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Deposit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Deposit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Loan_Amount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Loan_Amount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Taken)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Taken)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Remain)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Remain)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Property.Property_Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Property.Property_Code)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Propertymanagerment/Propertymanagerment/Areas/Admin/Views/InstallmentContract/Details.cshtml
@model Propertymanagerment.Models.Installment_Contract

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Installment_Contract</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Installment_Contract_Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Installment_Contract_Code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Customer_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customer_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Year_Of_Birth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Year_Of_Birth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SSN)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SSN)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Customer_Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customer_Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Mobile)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mobile)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date_Of_Contract)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date_Of_Contract)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Installment_Payment_Method)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Installment_Payment_Method)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Payment_Period)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Payment_Period)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Deposit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Deposit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Loan_Amount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Loan_Amount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Taken)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Taken)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Remain)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Remain)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Property.Property_Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Property.Property_Code)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Propertymanagerment/Propertymanagerment/Areas/Admin/Views/InstallmentContract/Index.cshtml
@model IEnumerable<Propertymanagerment.Models.Installment_Contract>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<title>Manager Installment Contract.</title>

<h2 style="text-align:center">VIEW LIST OF INSTALLMENT CONTRACT</h2>
@if (Session["success"] != null)
{
    <div class="alert alert-success alert-dismissible" role="alert">

        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <strong>Well done!</strong> @Session["success"]
    </div>
}

<p>
    @Html.ActionLink("Thêm bất động sản", "Create", null, new { @class = "btn btn-primary" })

</p>

<table class="table table-bordered table-striped" id="example1">
    <thead>
        <tr>
            <th>INSTALLMENT CONTRACT CODE</th>
            <th>CUSTOMER NAME</th>
            <th>SSN</th>
            <th>PROPERTY CODE</th>
            <th>MOBILE</th>
            <th>DATE OF CONTRACT</th>
            <th></th>
        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Installment_Contract_Code)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Customer_Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SSN)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Property.Property_Code)

                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Mobile)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Date_Of_Contract)
                </td>
                <td>
                    <a href="@Url.Action("Print", "InstallmentContract", new { id = item.ID })" target="_blank">
                        <button style="font-weight: bold">
                            <span class="fa fa-print">Print</span>
                        </button>
                    </a>

                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <th>FULL CONTRACT CODE</th>
            <th>CUSTOMER NAME</th>
            <th>SSN</th>
            <th>PROPERTY CODE</th>
            <th>MOBILE</th>
            <th>DATE OF CONTRACT</th>
            <th></th>
        </tr>
    </tfoot>
</table>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $(function () {
            $(document).on('click', '[data-toggle="lightbox"]', function (event) {
                event.preventDefault();
                $(this).ekkoLightbox({
                    alwaysShowClose: true
                });
            });

            $('.filter-container').filterizr({ gutterPixels: 3 });
            $('.btn[data-filter]').on('click', function () {
                $('.btn[data-filter]').removeClass('active');
                $(this).addClass('active');
            });
        })
    </script>
}

Propertymanagerment/Propertymanagerment/Areas/Admin/Views/InstallmentContract/Print.cshtml
@model Propertymanagerment.Models.InstallmentContractPrintModel
@{
    ViewBag.Title = "Print";
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Print</title>
    <link rel="stylesheet" href="~/Content/style.css" media="all" />
    <link href="~/Content/style.css" rel="stylesheet" />
    <a href="~/webfonts/SourceSansPro-Regular.ttf"></a>

</head>
<body>
    <header class="clearfix">
        <div id="logo">

            <img src="~/Images/PPCLogo.png" />
        </div>
        <div id="company">
            <h2 class="name">Công ty PPC</h2>
            <div> VĂN LANG CƠ SỞ 3</div>
            <div>091-519-0450</div>
            <div><a href="team2@vanlanguni.edu.vn">TEAM 2</a></div>
        </div>
    </header>
    <main>
        <div>
            <h1 style="text-align:center; color:#57B223">HỢP ĐỒNG MUA BẤT ĐỘNG SẢN TRẢ GÓP</h1>
            <h2 class="contract">@Model.Installment_Contract_Code</h2>
            <h4 class="date"> <i> Hôm nay, Ngày @String.Format("{0: dd/MM/yyyy}", Model.Date_Of_Contract) . Chúng tôi gồm: </i></h4>
        </div>
        <div id="details" class="clearfix">
            <table border="1">
                <tr>
                    <td style="border-right:1px solid black">
                        <div id="client">
                            <div class="to">BÊN A:</div>
                            <h2 class="company">Công ty PPC</h2>
                            <div class="address">VĂN LANG CƠ SỞ 3</div>
                            <div class="mobile">091-519-0450</div>
                            <div class="tax">000-519-0450</div>
                        </div>
                    </td>
                    <td>
                        <div id="invoice">
                            <div class="to">BÊN B:</div>
                            <h2 class="customername">@Model.Customer_Name</h2>
                            <div class="customeraddress">@Model.Customer_Address</div>
                            <div class="customermobile">@Model.Mobile</div>
                            <div class="ssn">@Model.SSN</div>
                        </div>
                    </td>
                </tr>
            </table>
        </div>
        <span>
            <h4>Sau khi bàn bạc, hai bên thống nhất ký kết Hợp đồng với các điều kiện và điều khoản như sau: </h4>
            <h4>Điều 1: Đối tượng của hợp đồng</h4>

            <div class="paddress">1. Đối tượng của hợp đồng này là ngôi nhà: <b class="property"> @Model.Address (Mã bất động sản: @Model.Property_Code)</b></div>
            2. Công ty PPC là chủ sở hữu nhà ở và sử dụng đất ở trên.

            <h4>Điều 2. Giá và phương thức thanh toán</h4>
            <div class="pprice"> 1. Giá mua bán toàn bộ căn nhà nêu trên là:<b class="money">@string.Format("{0:0,0} VND", Model.Price)</b>.</div>
            <div class="pdeposit">2. Bên B đã đặt cọc cho Bên A số tiền: <b class="money">@string.Format("{0:0,0} VND", Model.Deposit)</b></div>
            3. Bên B thanh toán số tiền còn lại một lần cho Bên A bằng đồng Việt Nam.
            4. Bên B giao và Bên A nhận đủ số tiền mua bán căn nhà nêu trên. Việc giao và nhận số tiền nêu trên do hai bên tự thực hiện và chịu trách nhiệm trước pháp luật.

            <h4>Điều 3. Điều khoản cuối cùng</h4>

            <p> 1. Hai bên đã hiểu rõ quyền, nghĩa vụ và lợi ích hợp pháp của mình, ý nghĩa và hậu quả pháp lý của việc công chứng này, sau khi đã được nghe lời giải thích của người có thẩm quyền công chứng hoặc chứng thực dưới đây. </p>

            <p> 2. Hai bên đã tự đọc lại hợp đồng này, đã hiểu và đồng ý tất cả các điều khoản ghi trong hợp đồng này.</p>

            <p> 3. Hợp đồng này được lập thành 02 bản. Bên A giữ 01 bản, Bên B giữ 01 bản</p>
        </span>
        <table style="text-align:center;">
            <tr>
                <td class="sign">
                    <h4> BÊN BÁN </h4>
                    </h3>(Ký và ghi rõ họ và tên)</h3>
                </td>
                <td class="sign">
                    <h4>BÊN MUA </h4>
                    </h3>(Ký và ghi rõ họ và tên)</h3>
                </td>
            </tr>
        </table>


    </main>
    <footer>
        Công ty ABC - Tài sản thực, giá trị thực.
    </footer>
</body>
</html>