Propertymanagerment/Propertymanagerment/Areas/Admin/Controllers/PropertyAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PropertyManagerment.Models;
using System.IO;
using System.Transactions;
using System.Data.Entity;

namespace PropertyManagerment.Areas.Admin.Controllers
{
    public class PropertyAdminController : Controller
    {
        PPCDBEntities model = new PPCDBEntities();
        // GET: Admin/PropertyAdmin
        public ActionResult Index()
        {
            var property = model.Properties.ToList();

            return View(property);
        }

        public ActionResult Create()
        {
            PopuparData();

            otherData();

            return View();
        }
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("index", "notfound");
            }
            Property property = model.Properties.FirstOrDefault(x => x.ID == id);

            if (property == null)
            {
                return RedirectToAction("index", "notfound");
            }
            return View(property);
        }
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("index", "notfound");
            }
            Property property = model.Properties.FirstOrDefault(x => x.ID == id);

            if (property == null)
            {
                return RedirectToAction("index", "notfound");
            }
            otherData(property.District.City_ID, model.Property_Service.Where(x => x.Property_ID == property.ID).Select(x => x.Service_ID));
            PopuparData(property.Property_Type_ID, property.District_ID, property.Property_Status_ID);
            return View(property);
        }

        public void PopuparData(object propertypeSelected = null, object districtSelected = null, object statusSelected = null)
        {
            ViewBag.Property_Type_ID = new SelectList(model.Property_Type.ToList(), "ID", "Property_Type_Name", propertypeSelected);
            ViewBag.District_ID = new SelectList(model.Districts.ToList(), "ID", "District_Name", districtSelected);
            ViewBag.Property_Status_ID = new SelectList(model.Property_Status.ToList(), "ID", "Property_Status_Name", statusSelected);

        }
        public void PopularMessage(bool success)
        {
            if (success == true)
            {
                Session["success"] = "Sucessfull";
            }

            else
            {
                Session["success"] = "Failed";
            }

        }
        [HttpPost]

        public ActionResult Create([Bind(Include = "Property_Name,Property_Type_ID,Description,District_ID,Address" +
            ",Area,Bed_Room,Bath_Room,Price,Installment_Rate,Avatar,Album,Property_Status_ID")]
        Property property, HttpPostedFileBase[] files, HttpPostedFileBase file
           , List<int> Service_ID)
        {

            if (ModelState.IsValid)
            {
                using (var scope = new TransactionScope())
                {

                    model.Properties.Add(property);

                    string album = "";
                    Random random = new Random();
                    if (files != null)
                    {
                        foreach (var imageFile in files)
                        {
                            if (imageFile != null)
                            {
                                var fileName = random.Next(1, 99999).ToString() + Path.GetFileName(imageFile.FileName);
                                var physicalPath = Path.Combine(Server.MapPath("~/Images/"), fileName);

                                // The files are not actually saved in this demo
                                imageFile.SaveAs(physicalPath);
                                album += album.Length > 0 ? ";" + fileName : fileName;
                            }
                        }
                    }
                    property.Album = album;
                    if (file != null)
                    {
                        var avatar = random.Next(1, 99999).ToString() + Path.GetFileName(file.FileName);
                        var physicPath = Path.Combine(Server.MapPath("~/Images/"), avatar);
                        file.SaveAs(physicPath);
                        property.Avatar = avatar;
                    }



                    foreach (var item in Service_ID)
                    {
                        Property_Service properS = new Property_Service();
                        properS.Property_ID = property.ID;
                        properS.Service_ID = item;
                        model.Property_Service.Add(properS);


                    }

                    model.SaveChanges();
                    scope.Complete();
                    PopularMessage(true);
                    return RedirectToAction("Index");

                }
            }
            otherData();
            PopuparData();
            PopularMessage(false);
            return View("Create", property);

        }

        [HttpPost]
        public ActionResult Edit(Property property, string Property_Name, int Property_Type_ID, string Description,
           string Address, int Area, int Bed_Room, int Bath_Room, decimal Price, double Installment_Rate, int District_ID, int Property_Status_ID, HttpPostedFileBase[] files, HttpPostedFileBase file
         , List<int> Service_ID)
        {
            if (ModelState.IsValid)
            {

                using (var scrope = new TransactionScope())
                {

                    property = model.Properties.FirstOrDefault(x => x.ID == property.ID);
                    string album = property.Album;
                    Random random = new Random();
                    if (files != null)
                    {
                        foreach (var imageFile in files)
                        {
                            if (imageFile != null)
                            {
                                var fileName = random.Next(1, 99999).ToString() + Path.GetFileName(imageFile.FileName);
                                var physicalPath = Path.Combine(Server.MapPath("~/Images"), fileName);

                                // The files are not actually saved in this demo
                                imageFile.SaveAs(physicalPath);
                                album += album.Length > 0 ? ";" + fileName : fileName;
                            }
                        }

                    }
                    property.Album = album;
                    // Avatar
                    if (file != null)
                    {
                        var avatar = random.Next(1, 99999).ToString() + Path.GetFileName(file.FileName);
                        var physicPath = Path.Combine(Server.MapPath("~/Images"), avatar);
                        file.SaveAs(physicPath);
                        property.Avatar = avatar;
                    }

                    // add model to database
                    property.Address = Address;
                    property.Area = Area;
                    property.Description = Description;
                    property.Bath_Room = Bath_Room;
                    property.Bed_Room = Bed_Room;
                    property.Installment_Rate = Installment_Rate;
                    property.Price = Price;
                    property.Property_Type_ID = Property_Type_ID;
                    property.Property_Name = Property_Name;
                    property.District_ID = District_ID;
                    property.Property_Status_ID = Property_Status_ID;


                    if (Service_ID != null)
                    {
                        var orn = model.Property_Service.Where(x => x.Property_ID == property.ID).ToArray();
                        for (int i = 0; i < orn.Length; i++)
                        {
                            var tmp = orn[i];
                            Property_Service psDell = model.Property_Service.FirstOrDefault(x => x.Property_ID == tmp.Property_ID);
                            model.Property_Service.Remove(psDell);
                            model.SaveChanges();
                        }
                    }

                    foreach (var item in Service_ID)
                    {
                        Property_Service properS = new Property_Service();
                        properS.Property_ID = property.ID;
                        properS.Service_ID = item;
                        model.Property_Service.Add(properS);
                        model.SaveChanges();
                    }
                    model.Entry(property).State = EntityState.Modified;
                    model.SaveChanges();
                    // save file to app_data
                    scrope.Complete();
                    // all done successfully

                    return RedirectToAction("Index");
                }
            }
            otherData();
            PopuparData();
            return View("Edit", property);
        }


        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    Property property = model.Properties.FirstOrDefault(x => x.ID == id);

        //    var orn = model.Property_Service.Where(x => x.Property_ID == property.ID).ToArray();
        //    for (int i = 0; i < orn.Length; i++)
        //    {
        //        var tmp = orn[i];
        //        Property_Service psDell = model.Property_Service.FirstOrDefault(x => x.Property_ID == tmp.Property_ID);
        //        model.Property_Service.Remove(psDell);
        //        model.SaveChanges();
        //    }
        //    model.Properties.Remove(property);
        //    model.SaveChanges();
        //    return RedirectToAction("Index");

        //}

Propertymanagerment/Propertymanagerment/Areas/Admin/Views/PropertyAdmin/Delete.cshtml
@model PropertyManagerment.Models.Property

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>XÓA BẤT ĐỘNG SẢN</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="@Url.Action("Index", "PropertyAdmin")">DANH SÁCH BẤT ĐỘNG SẢN</a></li>
                    <li class="breadcrumb-item active">XÓA BẤT ĐỘNG SẢN</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>
<div>

    @*<dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Property_Code)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Property_Code)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Property_Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Property_Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Address)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Address)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Area)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Area)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Bed_Room)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Bed_Room)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Bath_Room)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Bath_Room)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Price)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Price)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Installment_Rate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Installment_Rate)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Avatar)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Avatar)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Album)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Album)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.District.District_Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.District.District_Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Property_Status.Property_Status_Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Property_Status.Property_Status_Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Property_Type.Property_Type_Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Property_Type.Property_Type_Name)
            </dd>

        </dl>*@

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.Raw(TempData["msg"])
        <div class="col-12">
            <div class="card card-danger">
                <div class="card-header">
                    <div class="card-title">
                        <h3 class="card-title">THÔNG TIN BẤT ĐỘNG SẢN</h3>
                    </div>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label> TÊN BẤT ĐỘNG SẢN</label>
                                <div class="col-md-10">
                                    @Html.DisplayFor(model => model.Property_Name)
                                </div>
                            </div>

                            <div class="form-group">
                                <label> LOẠI BẤT ĐỘNG SẢN</label>
                                <div class="col-md-10">
                                    @Html.DisplayFor(model => model.Property_Type.Property_Type_Name)
                                </div>
                            </div>

                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label> CHỌN TỈNH THÀNH  </label>
                                <div class="col-md-10">
                                    @Html.DisplayFor(model => model.District.District_Name)
                                </div>
                            </div>
                            <div class="form-group">
                                <label> MÔ TẢ BẤT ĐỘNG SẢN  </label>
                                <div class="col-md-10">
                                    @Html.DisplayFor(model => model.Description)
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Delete" class="btn btn-warning" style="margin-left:5%" />
                <div class="btn btn-primary" style="margin-left:50%">@Html.ActionLink("Quay lại", "Index")</div>
            </div>
        </div>
    }
</div>

Propertymanagerment/Propertymanagerment/Areas/Admin/Views/PropertyAdmin/Details.cshtml
@model Propertymanagerment.Models.Property

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<title>Xem Chi Tiết Bất Động Sản @Model.Property_Code</title>

<style>
    img {
        width: 150px;
        height: 150px;
    }

    h2 {
        margin-top: 5px;
        margin-bottom: -10px;
        text-align: center;
        font-weight: bold;
    }

    th {
        color: chocolate;
    }

    tr:hover {
        background-color: chartreuse;
    }

    .btn-primary:hover {
        font-weight: bold;
        color: yellow;
    }

    .btn-default:hover {
        font-weight: bold;
        color: chocolate;
    }
</style>

<h2 style="color:royalblue">Chi Tiết Bất Động Sản</h2>

<div>
    <hr />
    <table class="table table-bordered success">
        <tr>
            <th>
                Property Code:
            </th>
            <td id="Large">
                @Html.DisplayFor(model => model.Property_Code)
            </td>
        </tr>

        <tr>
            <th>
                Property Name:
            </th>
            <td id="Large">
                @Html.DisplayFor(model => model.Property_Name)
            </td>
        </tr>

        <tr>
            <th>
                Property Type:
            </th>
            <td id="Large">
                @Html.DisplayFor(model => model.Property_Type.Property_Type_Name)
            </td>
        </tr>

        <tr>
            <th>
                Description:
            </th>
            <td id="Large">
                @Html.DisplayFor(model => model.Description)
            </td>
        </tr>

        <tr>
            <th>
                District:
            </th>
            <td id="Large">
                @Html.DisplayFor(model => model.District.District_Name)
            </td>
        </tr>

        <tr>
            <th>
                Address:
            </th>
            <td id="Large">
                @Html.DisplayFor(model => model.Address)
            </td>
        </tr>

        <tr>
            <th>
                Area:
            </th>
            <td id="Large">
                @Html.DisplayFor(model => model.Area)
            </td>
        </tr>

        <tr>
            <th>
                Bed Room:
            </th>
            <td id="Large">
                @Html.DisplayFor(model => model.Bed_Room)
            </td>
        </tr>

        <tr>
            <th>
                Bath Room:
            </th>
            <td id="Large">
                @Html.DisplayFor(model => model.Bath_Room)
            </td>
        </tr>

        <tr>
            <th>
                Price:
            </th>
            <td id="Large">
                @Html.DisplayFor(model => model.Price)
            </td>
        </tr>

        <tr>
            <th>
                Installment Rate:
            </th>
            <td id="Large">
                @Html.DisplayFor(model => model.Installment_Rate)%
            </td>
        </tr>

        <tr>
            <th>
                Avatar:
            </th>
            <td id="Large">
                <img src="@Url.Action("Image", new { id = Model.ID }) " />
            </td>
        </tr>

        <tr>
            <th>
                Album:
            </th>
            <td id="Large">
                <img src="@Url.Action("Image", new { id = Model.ID }) " />
                <img src="@Url.Action("Image1", new { id = Model.ID }) " />
                <img src="@Url.Action("Image2", new { id = Model.ID }) " />
            </td>
        </tr>

        <tr>
            <th>
                Property Status:
            </th>
            <td id="Large">
                @Html.DisplayFor(model => model.Property_Status.Property_Status_Name)
            </td>
        </tr>
    </table>
</div>

<div class="form-group">
    <div class="col-md-offset-2 col-md-10">
        @Html.ActionLink("Navigate to Edit", "Edit", new { id = Model.ID }, new { @class = "btn btn-primary" }) |
        @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default" })
    </div>
</div>

Propertymanagerment/Propertymanagerment/Areas/Admin/Views/PropertyAdmin/Index.cshtml
@model IEnumerable<PropertyManagerment.Models.Property>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
    .dropbtn {
        background-color: teal;
        color: white;
        padding: 15px;
        font-size: 13px;
        border: none;
    }

    .dropup {
        position: relative;
        display: inline-block;
    }

    .dropup-content {
        display: none;
        position: absolute;
        background-color: #f1f1f1;
        min-width: 160px;
        bottom: 50px;
        z-index: 1;
    }

        .dropup-content a {
            color: black;
            padding: 12px 16px;
            text-decoration: none;
            display: block;
        }

            .dropup-content a:hover {
                background-color: #ccc
            }

    .dropup:hover .dropup-content {
        display: block;
    }

    .dropup:hover .dropbtn {
        background-color: #2980B9;
    }

    .btn-group button {
        background-color: #4CAF50; /* Green background */
        border: 1px solid green; /* Green border */
        color: white; /* White text */
        padding: 10px 24px; /* Some padding */
        cursor: pointer; /* Pointer/hand icon */
        float: left; /* Float the buttons side by side */
    }

    /* Clear floats (clearfix hack) */
    .btn-group:after {
        content: "";
        clear: both;
        display: table;
    }

    .btn-group button:not(:last-child) {
        border-right: none; /* Prevent double borders */
    }

    /* Add a background color on hover */
    .btn-group button:hover {
        background-color: #3e8e41;
    }
</style>

<h2 style="text-align:center">DANH SÁCH BẤT ĐỘNG SẢN</h2>
@if (Session["success"] != null)
{
    <div class="alert alert-success alert-dismissible" role="alert">

        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <strong>Well done!</strong> @Session["success"]
    </div>
}

<p>
    @Html.ActionLink("Thêm bất động sản", "Create", null, new { @class = "btn btn-primary" })

</p>


<table id="example1" class="table table-bordered table-striped">
    <thead>
        <tr class="thead-dark" align=" center">
            <th>Mã BĐS</th>
            <th>Tên BĐS</th>
            <th>Ảnh đại diện</th>
            <th>Giá tiền</th>
            <th>Trạng thái</th>
            <th>

            </th>
            <th>

            </th>
            <th>

            </th>
        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model)
        {
            <tr align="center">
                <td>
                    @Html.DisplayFor(modelItem => item.Property_Code)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Property_Name)
                </td>
                <td>
                    <a href="@(Url.Content("~/Images/" + item.Avatar))" data-toggle="lightbox" data-gallery="gallery">
                        @if (!String.IsNullOrEmpty(item.Avatar) && item.Avatar != "")
                        {<img src="@(Url.Content("~/Images/" + item.Avatar))" width="200" />}
                    </a>
                </td>
                <td>
                    @string.Format("{0:0,0} VND", @Html.DisplayFor(modelItem => item.Price))

                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Property_Status.Property_Status_Name)
                </td>

                <td>
                    <button type="button" class="btn btn-primary"> @Html.ActionLink("Cập nhật", "Edit", new { id = item.ID }) </button>
                </td>
                <td>
                    @if (item.Full_Contract.FirstOrDefault(m => m.Property_ID == item.ID) != null || item.Installment_Contract.FirstOrDefault(m => m.Property_ID == item.ID) != null)
                    {
                        <button onclick="document.getElementById('id01').style.display='block'" class="w3-button w3-black" title="Đã có hợp đồng" disabled>
                            Thêm hợp đồng
                        </button>
                    }
                    else
                    {
                        <div class="dropup">
                            <button class="dropbtn">Thêm hợp đồng</button>
                            <div class="dropup-content">
                                <a href="@Url.Action("Create", "Installment_ContractAdmin", new { id = item.ID })">Hợp đồng trả góp</a>
                                <a href="@Url.Action("Create", "Full_ContractAdmin", new { id = item.ID })">Hợp đồng đầy đủ</a>
                            </div>
                        </div>
                    }
                    </td>
                <td>
                    @Html.ActionLink(" ", "Delete", new { id = item.ID }, new { @class = "fa fa-trash" })
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr align="center" class="thead-dark">
            <th>Mã BĐS</th>
            <th>Tên BĐS</th>
            <th>Ảnh đại diện</th>
            <th>Giá tiền</th>
            <th>Trạng thái</th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
    </tfoot>
</table>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    


}