Propertymanagerment/Propertymanagerment/Models/Full_Contract.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Propertymanagerment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Full_Contract
    {
        public int ID { get; set; }
        public string Full_Contract_Code { get; set; }
        public string Customer_Name { get; set; }
        public Nullable<int> Year_Of_Birth { get; set; }
        public string SSN { get; set; }
        public string Customer_Address { get; set; }
        public string Mobile { get; set; }
        public int Property_ID { get; set; }
        public Nullable<System.DateTime> Date_Of_Contract { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Deposit { get; set; }
        public Nullable<decimal> Remain { get; set; }
        public bool Status { get; set; }
    
        public virtual Property Property { get; set; }
    }
}

Propertymanagerment/Propertymanagerment/Areas/Admin/Controllers/FullContractController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Propertymanagerment.Models;

namespace PropertyManagerment.Areas.Admin.Controllers
{
    public class FullContractController : Controller
    {
        private PPCDBEntities db = new PPCDBEntities();

        // GET: Admin/Full_Contract
        public ActionResult Index()
        {
            var full_Contract = db.Full_Contract.Include(f => f.Property);
            return View(full_Contract.ToList());
        }

        // GET: Admin/Full_Contract/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Full_Contract full_Contract = db.Full_Contract.Find(id);
            if (full_Contract == null)
            {
                return HttpNotFound();
            }
            return View(full_Contract);
        }

        // GET: Admin/Full_Contract/Create
        public ActionResult Create()
        {
            ViewBag.Property_ID = new SelectList(db.Properties, "ID", "Property_Code");
            return View();
        }

        // POST: Admin/Full_Contract/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Full_Contract_Code,Customer_Name,Year_Of_Birth,SSN,Customer_Address,Mobile,Property_ID,Date_Of_Contract,Price,Deposit,Remain,Status")] Full_Contract full_Contract)
        {
            if (ModelState.IsValid)
            {
                db.Full_Contract.Add(full_Contract);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Property_ID = new SelectList(db.Properties, "ID", "Property_Code", full_Contract.Property_ID);
            return View(full_Contract);
        }

        // GET: Admin/Full_Contract/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Full_Contract full_Contract = db.Full_Contract.Find(id);
            if (full_Contract == null)
            {
                return HttpNotFound();
            }
            ViewBag.Property_ID = new SelectList(db.Properties, "ID", "Property_Code", full_Contract.Property_ID);
            return View(full_Contract);
        }

        // POST: Admin/Full_Contract/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Full_Contract_Code,Customer_Name,Year_Of_Birth,SSN,Customer_Address,Mobile,Property_ID,Date_Of_Contract,Price,Deposit,Remain,Status")] Full_Contract full_Contract)
        {
            if (ModelState.IsValid)
            {
                db.Entry(full_Contract).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Property_ID = new SelectList(db.Properties, "ID", "Property_Code", full_Contract.Property_ID);
            return View(full_Contract);
        }

        // GET: Admin/Full_Contract/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Full_Contract full_Contract = db.Full_Contract.Find(id);
            if (full_Contract == null)
            {
                return HttpNotFound();
            }
            return View(full_Contract);
        }

        // POST: Admin/Full_Contract/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Full_Contract full_Contract = db.Full_Contract.Find(id);
            db.Full_Contract.Remove(full_Contract);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult Print(int id)
        {
            var contract = db.Full_Contract.FirstOrDefault(n => n.ID == id);
            if (contract != null)
            {
                FullContractPrintModel fc = new FullContractPrintModel();
                fc.Customer_Name = contract.Customer_Name;
                fc.Customer_Address = contract.Customer_Address;
                fc.Date_Of_Contract = contract.Date_Of_Contract;
                fc.Deposit = contract.Deposit;
                fc.Mobile = contract.Mobile;
                fc.Price = contract.Price;
                fc.Property_Code = contract.Property.Property_Code;
                fc.SSN = contract.SSN;
                fc.Address = contract.Property.Address; ;
                fc.Full_Contract_Code = contract.Full_Contract_Code;
                return View(fc);
            }
            else
            {
                return View();
            }
        }
    }
}

Propertymanagerment/Propertymanagerment/Areas/Admin/Views/FullContract/Create.cshtml
@model Propertymanagerment.Models.Full_Contract

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Full_Contract</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Full_Contract_Code, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Full_Contract_Code, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Full_Contract_Code, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Customer_Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Customer_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Customer_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Year_Of_Birth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Year_Of_Birth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Year_Of_Birth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SSN, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SSN, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SSN, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Customer_Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Customer_Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Customer_Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mobile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mobile, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mobile, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Property_ID, "Property_ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Property_ID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Property_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date_Of_Contract, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date_Of_Contract, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date_Of_Contract, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Deposit, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Deposit, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Deposit, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Remain, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Remain, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Remain, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Status)
                    @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Propertymanagerment/Propertymanagerment/Areas/Admin/Views/FullContract/Delete.cshtml
@model Propertymanagerment.Models.Full_Contract

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Full_Contract</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Full_Contract_Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Full_Contract_Code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Customer_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customer_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Year_Of_Birth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Year_Of_Birth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SSN)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SSN)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Customer_Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customer_Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Mobile)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mobile)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date_Of_Contract)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date_Of_Contract)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Deposit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Deposit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Remain)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Remain)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Property.Property_Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Property.Property_Code)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Propertymanagerment/Propertymanagerment/Areas/Admin/Views/FullContract/Details.cshtml
@model Propertymanagerment.Models.Full_Contract

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Full_Contract</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Full_Contract_Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Full_Contract_Code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Customer_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customer_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Year_Of_Birth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Year_Of_Birth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SSN)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SSN)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Customer_Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customer_Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Mobile)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mobile)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date_Of_Contract)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date_Of_Contract)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Deposit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Deposit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Remain)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Remain)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Property.Property_Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Property.Property_Code)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Propertymanagerment/Propertymanagerment/Areas/Admin/Views/FullContract/Edit.cshtml
@model Propertymanagerment.Models.Full_Contract

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Full_Contract</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Full_Contract_Code, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Full_Contract_Code, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Full_Contract_Code, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Customer_Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Customer_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Customer_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Year_Of_Birth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Year_Of_Birth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Year_Of_Birth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SSN, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SSN, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SSN, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Customer_Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Customer_Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Customer_Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mobile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mobile, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mobile, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Property_ID, "Property_ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Property_ID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Property_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date_Of_Contract, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date_Of_Contract, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date_Of_Contract, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Deposit, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Deposit, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Deposit, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Remain, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Remain, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Remain, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Status)
                    @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Propertymanagerment/Propertymanagerment/Areas/Admin/Views/FullContract/Index.cshtml
@model IEnumerable<Propertymanagerment.Models.Full_Contract>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<title>Manager Full Contract.</title>

<h2 style="text-align:center">VIEW LIST OF FULL CONTRACT</h2>
@if (Session["success"] != null)
{
    <div class="alert alert-success alert-dismissible" role="alert">

        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <strong>Well done!</strong> @Session["success"]
    </div>
}

<p>
    @Html.ActionLink("Thêm bất động sản", "Create", null, new { @class = "btn btn-primary" })

</p>
<table class="table table-bordered table-striped" id="example1">
    <thead>
        <tr>
            <th>FULL CONTRACT CODE</th>
            <th>CUSTOMER NAME</th>
            <th>SSN</th>
            <th>PROPERTY CODE</th>
            <th>MOBILE</th>
            <th>DATE OF CONTRACT</th>
            <th></th>
        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Full_Contract_Code)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Customer_Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SSN)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Property.Property_Code)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Mobile)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Date_Of_Contract)
                </td>
                <td>
                    <a href="@Url.Action("Print", "FullContract", new { id = item.ID })" target="_blank">
                        <button style="font-weight: bold">
                            <span class="fa fa-print">Print</span>
                        </button>
                    </a>
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <th>FULL CONTRACT CODE</th>
            <th>CUSTOMER NAME</th>
            <th>SSN</th>
            <th>PROPERTY CODE</th>
            <th>MOBILE</th>
            <th>DATE OF CONTRACT</th>
            <th></th>
        </tr>
    </tfoot>
</table>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $(function () {
            $(document).on('click', '[data-toggle="lightbox"]', function (event) {
                event.preventDefault();
                $(this).ekkoLightbox({
                    alwaysShowClose: true
                });
            });

            $('.filter-container').filterizr({ gutterPixels: 3 });
            $('.btn[data-filter]').on('click', function () {
                $('.btn[data-filter]').removeClass('active');
                $(this).addClass('active');
            });
        })
    </script>
}